config/routes.rb
Pqrs::Application.routes.draw do
 

resources :users do
  match '/get_collections/' => 'users#get_collections', :via => :get
  match '/get_qrcodes/' => 'users#get_qrcodes', :via => :get
end

resources :qrcodes do
  match '/show_image/' => 'qrcodes#show_image', :via => :get
  resources :comments
  resources :qrcontents
end

resources :collections do
  match '/add_qr/:qrcode_id' => 'collections#add_qr',
         :via => :post
  match '/qrcodes/' => 'collections#get_qrcodes', :via => :get
  match '/qrcodes/new' => 'collections#new_qrcode', :via => :post
end 

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :qr_collection_placements, dependent: :destroy
  has_many :qrcodes, through: :qr_collection_placements
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :authenticate, :except => [:get_qrcodes]
    
  def new_qrcode
    ## NEED TO ADD PROCESS OF ADDING QR CODE TO USER LIST OF QR
    ## CODES AND THEN ADDING IT TO THE COLLECTION
    #@qr = User.qrcodes.new
    
  end
  #Get all QR Codes for a collection 
  def get_qrcodes
    @collection = Collection.find(params[:collection_id])
    @qrcodes = @collection.qrcodes
    respond_to do |format|
      format.html
      format.json { render json: [@collections, @qrcodes] }
    end
  end

  def add_qr
    @collection = Collection.find(params[:collection_id])
    @qr = @current_user.qrcodes.find(params[:qrcode_id])

    @collection.qrcodes << @qr
    if @collection.save
      respond_to do |format|
        format.html { redirect_to user_collection_qrcodes_path, 
                      notice: 'QR Code added to collection successfully.' }
        format.json { render json: [@current_user, @collection, @qr] }
      end
    end
  end

  # GET /collections
  # GET /collections.json
  def index
    ### WHAT IF ANOTHER USER IS TRYING TO LOOK AT
    #   ANOTHER USER'S COLLECTION?
    #
    @collections = @current_user.collections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show

    @collection = @current_user.collections.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  # NOT NEEDED
  def new
    @collection = @user.collections.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = @user.collections.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  # ADD COLLECTION BY ATTRIBUTES TOO
  def create
    @collection = @current_user.collections.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to [@current_user, @collection],
		      notice: 'Collection was successfully created.' }
        format.json { render json: [@current_user, @collection], 
		      status: :created, 
                      location: [@current_user,  @collection] }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, 
		      status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = @current_user.collections.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to [@current_user, @collection],
                      notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, 
                      status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = @current_user.collections.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to user_collections_path,
  		    notice: 'Collection sucessfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for([@user,@collection]) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/_qrform.html.erb
<%= form_for([@user, @collection, @qrcode]) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved: </h2>
      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label(:qrcode, :name) %><br />
    <%= f.text_fiel(:qrcode, :name) %><br />
  </div>i
  <div class="actions">
    <%= f.submit %>
  </div>
<%end>

app/views/collections/add_qr.html.erb
<p>Hello</p>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @collection] %> |
<%= link_to 'Back', user_collections_path(@user) %>

app/views/collections/get_qrcodes.html.erb
<h1>QR Codes for Collection <%= @collection.name%></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Hits</th>
    <th>Geolong</th>
    <th>Geolat</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qrcodes.each do |qrcode| %>
  <tr>
    <td><%= qrcode.name %></td>
    <td><%= qrcode.description %></td>
    <td><%= qrcode.hits %></td>
    <td><%= qrcode.geoLong %></td>
    <td><%= qrcode.geoLat %></td>
    <td><%= qrcode.image %></td>
    <td><%= link_to 'Show', [@user, qrcode] %></td>
    <td><%= link_to 'Edit', edit_user_qrcode_path(@user, qrcode) %></td>
    <td><%= link_to 'Destroy', [@user, qrcode], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create New Qrcode For Collection', user_collection_qrcodes_new_path([@user, @collection]) %>

app/views/collections/index.html.erb
<h1>Listing collections</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @collections.each do |collection| %>
  <tr>
    <td><%= collection.name %></td>
    <td><%= collection.description %></td>
    <td><%= link_to 'Show', user_collection_path(@user, collection) %></td>
    <td><%= link_to 'Edit', edit_user_collection_path(@user, collection) %></td>
    <td><%= link_to 'Destroy', [@user, collection], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Collection', new_user_collection_path(@user) %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', user_collections_path(@user) %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @collection.name %>
</p>

<p>
  <b>Description:</b>
  <%= @collection.description %>
</p>


<%= link_to 'Edit', edit_user_collection_path(@user, @collection) %> |
<%= link_to 'Back', user_collections_path(@user) %>