config/routes.rb
Pqrs::Application.routes.draw do
 

resources :users do
  match '/get_collections/' => 'users#get_collections', :via => :get
  match '/get_qrcodes/' => 'users#get_qrcodes', :via => :get
end

resources :qrcodes do
  match '/show_image/' => 'qrcodes#show_image', :via => :get
  resources :comments
  resources :qrcontents
end

resources :collections do
  match '/add_qr/:qrcode_id' => 'collections#add_qr',
         :via => :post
  match '/qrcodes/' => 'collections#get_qrcodes', :via => :get
  match '/qrcodes/new' => 'collections#new_qrcode', :via => :post
end 

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :qrcodes, dependent: :destroy
  has_many :collections, dependent: :destroy
  has_one :google, :class_name=>"GoogleToken", :dependent=> :destroy
	
	def name
		"#{first_name} #{last_name}"
	end

	def to_s
		"id:'#{id}',uuid:'#{uuid}',email:'#{email}',created_at:'#{created_at}',updated_at:'#{updated_at}',first_name:'#{first_name}',last_name:'#{last_name}'"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:create, :get_collections, 
                                           :get_qrcodes]
  before_filter :get_user

  def get_user
    @user = User.find(params[:user_id])
  end  
  # GET /users/1/get_collections.json
  def get_collections
    #@user = User.find(params[:user_id])
    if !@user.nil?
      @collections = @user.collections
      if !@collections.nil?
        render json: @user.to_json(:include => { :collections => { :only => 
                                  [:name, :description] } }, :only => 
                                  [:first_name, :last_name])
      end
    end
  end
  
  # GET /users/1/get_qrcodes.json
  def get_qrcodes
    #@user = User.find(params[:user_id])
    if !@user.nil?
      @qrcodes = @user.qrcodes
      if !@qrcodes.nil?
        render json: @user.to_json(:include => { :qrcodes => { :except => 
                                  [:id, :user_id, :updated_at] } }, :only => 
                                  [:first_name, :last_name])
      end
    end
  end 

  
  # GET /users
  # GET /users.json
  ##########NOT NEEDED#######################
  def index
    #Added includes(:qrcode) to see how it works
    @users = User.includes(:qrcodes).all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  # ################NOT NEEDED#####################
  def show
    #@user = User.find(params[:id])
    
    if !@user.nil?
      #render json: @user.to_json(only: [:first_name, :last_name])
    
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    #@user = User.new

    respond_to do |format|
      #format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  ################NOT NEEDED###################
  def edit
    #@user = User.find(params[:id])
  end
  # POST /users
  # POST /users.json
  def create
    @client = OAuth2::Client.new('1074911058218.apps.googleusercontent.com', 
              'h_F3c5y8DXnNRgpfpnwkixbC', :site=>'https://accounts.google.com')

    begin
      @token = OAuth2::AccessToken.from_hash(@client,
               :access_token=> params[:token])

      response = @token.get('https://www.googleapis.com/oauth2/v1/userinfo')
      data = response.parsed
    end
    if User.find_by_google_id(data['id']).nil? 
      @user = User.new(:email=>data['email'], :google_id=>data['id'],
                       :first_name=>data['given_name'], 
                       :last_name=>data['family_name'])
      respond_to do |format|
        if @user.save
          format.json { render json: @user, status: :created, location: @user }
        else
          format.json { render json: @user.errors, 
                                            status: :unprocessable_entity }
        end
      end
    else 
       render json: @user, location: @user
    end  
  end

  # PUT /users/1
  # PUT /users/1.json
  #
  # NEED TO FIX THE USER_UUPDATE_ATTRIBUTES TO 
  # ACCEPT NAME CHANGES AND SUCH
  def update
    #@user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # NOT NEEDED
  def destroy
    #@user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Uuid</th>
    <th>Email</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>QR Code Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.uuid %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.qrcodes.first.name if user.qrcodes.count > 0%><td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uuid:</b>
  <%= @user.uuid %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First Name:</b>
  <%= @user.first_name %>
</p>
<p>
  <b>Last Name:</b>
  <%= @user.last_name %>
</p>

<%= link_to 'Create Collection', new_user_collection_path(@user) %> |
<%= link_to 'Create QR Code', new_user_qrcode_path(@user) %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>