config/routes.rb
Pqrs::Application.routes.draw do
 

resources :users do
  match '/get_collections/' => 'users#get_collections', :via => :get
  match '/get_qrcodes/' => 'users#get_qrcodes', :via => :get
end

resources :qrcodes do
  match '/show_image/' => 'qrcodes#show_image', :via => :get
  resources :comments
  resources :qrcontents
end

resources :collections do
  match '/add_qr/:qrcode_id' => 'collections#add_qr',
         :via => :post
  match '/qrcodes/' => 'collections#get_qrcodes', :via => :get
  match '/qrcodes/new' => 'collections#new_qrcode', :via => :post
end 

end

app/models/qrcontent.rb
class Qrcontent < ActiveRecord::Base
  has_many :qr_content_placements, dependent: :destroy
  has_many :qrcodes, through: :qr_content_placements
  has_one :content
end

app/controllers/qrcontents_controller.rb
class QrcontentsController < ApplicationController
  before_filter :get_qr

  def get_qr
    @qr = Qrcode.find(params[:qrcode_id])
  end
  # GET /qrcontents
  # GET /qrcontents.json
  def index
    @qrcontents = @qr.qrcontents

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qrcontents }
    end
  end

  # GET /qrcontents/1
  # GET /qrcontents/1.json
  def show
    @qrcontent = @qr.qrcontents.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qrcontent }
    end
  end

  # GET /qrcontents/new
  # GET /qrcontents/new.json
  def new
    @qrcontent = Qrcontent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qrcontent }
    end
  end

  # GET /qrcontents/1/edit
  def edit
    @qrcontent = Qrcontent.find(params[:id])
  end

  # POST /qrcontents
  # POST /qrcontents.json
  def create
    @qrcontent = @qr.qrcontents.new(params[:qrcontent])

    respond_to do |format|
      if @qrcontent.save
        format.html { redirect_to @qrcontent, 
                      notice: 'Qrcontent was successfully created.' }
        format.json { render json: @qrcontent, 
                      status: :created, location: @qrcontent }
      else
        format.html { render action: "new" }
        format.json { render json: @qrcontent.errors, 
                      status: :unprocessable_entity }
      end
    end
    ###not sure if this works#####
    params[:qrcontents][:qrcontent].each do |qc|
      @qrcontents = @qr.qrcontents.new(qc)
    end
  end

  # PUT /qrcontents/1
  # PUT /qrcontents/1.json
  def update
    @qrcontent = @qr.qrcontents.find(params[:id])

    respond_to do |format|
      if @qrcontent.update_attributes(params[:qrcontent])
        format.html { redirect_to @qrcontent, notice: 'Qrcontent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qrcontent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qrcontents/1
  # DELETE /qrcontents/1.json
  def destroy
    @qrcontent = Qrcontent.find(params[:id])
    @qrcontent.destroy

    respond_to do |format|
      format.html { redirect_to qrcontents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/qrcontents_helper.rb
module QrcontentsHelper
end

app/views/qrcontents/_form.html.erb
<%= form_for(@qrcontent) do |f| %>
  <% if @qrcontent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qrcontent.errors.count, "error") %> prohibited this qrcontent from being saved:</h2>

      <ul>
      <% @qrcontent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qrcontents/edit.html.erb
<h1>Editing qrcontent</h1>

<%= render 'form' %>

<%= link_to 'Show', @qrcontent %> |
<%= link_to 'Back', qrcontents_path %>

app/views/qrcontents/index.html.erb
<h1>Listing qrcontents</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qrcontents.each do |qrcontent| %>
  <tr>
    <td><%= qrcontent.url %></td>
    <td><%= qrcontent.content %></td>
    <td><%= link_to 'Show', qrcontent %></td>
    <td><%= link_to 'Edit', edit_qrcontent_path(qrcontent) %></td>
    <td><%= link_to 'Destroy', qrcontent, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qrcontent', new_qrcontent_path %>

app/views/qrcontents/new.html.erb
<h1>New qrcontent</h1>

<%= render 'form' %>

<%= link_to 'Back', qrcontents_path %>

app/views/qrcontents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @qrcontent.url %>
</p>

<p>
  <b>Content:</b>
  <%= @qrcontent.content %>
</p>


<%= link_to 'Edit', edit_qrcontent_path(@qrcontent) %> |
<%= link_to 'Back', qrcontents_path %>